/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DES;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.CipherInputStream;
import javax.crypto.CipherOutputStream;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.DESKeySpec;
import javax.swing.JOptionPane;

/**
 *
 * @author nhoct
 */
public class frm_Des extends javax.swing.JFrame {

    /**
     * Creates new form frm_Des
     */
    public frm_Des() {
        initComponents();
    }    
    
//------------------------------------------------------------------------------
    //Hàm doCopy    
    private int mode;
    private static void doCopy (InputStream is, OutputStream os) throws IOException{
        byte[] bytes = new byte[64];
        int numBytes;
        while ((numBytes = is.read(bytes)) != -1) {
            os.write(bytes, 0, numBytes);
        }
        os.flush();
        os.close();
        is.close();
    }
    //Hàm Mã hóa và Giải mã    
    public static void encrypt (String key, InputStream is, OutputStream os) throws Throwable { 
        encryptOrDecrypt (key, Cipher.ENCRYPT_MODE, is, os);
    }    
    //Hàm Giải mã   
    public static void decrypt (String key, InputStream is, OutputStream os) throws Throwable {
        encryptOrDecrypt (key, Cipher.DECRYPT_MODE, is, os);
    }  
    //Hàm thực hiện    
    public static void encryptOrDecrypt (String key, int mode, InputStream is, OutputStream os) throws Throwable {
        DESKeySpec dks = new DESKeySpec (key.getBytes());
        SecretKeyFactory skf = SecretKeyFactory.getInstance("DES"); 
        SecretKey desKey = skf.generateSecret (dks);
        Cipher cipher = Cipher.getInstance("DES"); // DES/ECB/PKCS5Padding for SunJCE

        if (mode == Cipher.ENCRYPT_MODE) {
            cipher.init(Cipher.ENCRYPT_MODE, desKey);
            CipherInputStream cis = new CipherInputStream(is, cipher); 
            doCopy(cis, os);
        } else if (mode == Cipher.DECRYPT_MODE) {
            cipher.init(Cipher.DECRYPT_MODE, desKey);
            CipherOutputStream cos = new CipherOutputStream(os, cipher); 
            doCopy(is, cos);
        }
    }
//------------------------------------------------------------------------------
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKhoa = new javax.swing.JTextField();
        btnMaHoa = new javax.swing.JButton();
        btnAllShow = new javax.swing.JButton();
        btnGhiFile = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtVanBan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMaHoa = new javax.swing.JTextField();
        btnGiaiMa = new javax.swing.JButton();
        btnMoFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("DES");

        jLabel2.setText("Input Key:");

        txtKhoa.setText("baomatthongtin");

        btnMaHoa.setText("Mã Hóa");
        btnMaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaActionPerformed(evt);
            }
        });

        btnAllShow.setText("All Show");
        btnAllShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllShowActionPerformed(evt);
            }
        });

        btnGhiFile.setText("Ghi File");
        btnGhiFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiFileActionPerformed(evt);
            }
        });

        jLabel3.setText("Plaintext:");

        txtVanBan.setText("I LOVE YOU MORE THAN I CAN SEE");

        jLabel4.setText("CipherText:");

        btnGiaiMa.setText("Giải Mã");
        btnGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaiMaActionPerformed(evt);
            }
        });

        btnMoFile.setText("Hiển Thị");
        btnMoFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 45, Short.MAX_VALUE)
                        .addComponent(btnMaHoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnMoFile)
                        .addGap(20, 20, 20)
                        .addComponent(btnGhiFile)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtKhoa)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVanBan)
                            .addComponent(txtMaHoa)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGiaiMa)
                .addGap(18, 18, 18)
                .addComponent(btnAllShow)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMaHoa)
                    .addComponent(btnGhiFile)
                    .addComponent(btnMoFile))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtVanBan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtMaHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGiaiMa)
                    .addComponent(btnAllShow))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//------------------------------------------------------------------------------
    private void btnMaHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaActionPerformed
        // TODO add your handling code here:
        try {
            String key=txtKhoa.getText(); // needs to be at least 8 characters for DES
            
            FileInputStream fis= new FileInputStream("M:\\Des.txt");
            FileOutputStream fos= new FileOutputStream("M:\\EnDes.txt"); 
            encrypt (key, fis, fos);
                JOptionPane.showMessageDialog(null," Đã mã hóa văn bản");
            //FileInputStream fis2= new FileInputStream("D:\\ThucHanh02\\testDES\\encrypted.txt"); 
            //FileOutputStream fos2= new FileOutputStream("D:\\ThucHanh02\\testDES\\decrypted.txt");
            // decrypt (key, fis2, fos2);
        } catch (Throwable e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnMaHoaActionPerformed
//------------------------------------------------------------------------------
    private void btnGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaiMaActionPerformed
        // TODO add your handling code here:        
        FileInputStream fis2 = null;
        try {
            String fileName = "M:\\Des.txt";
            String key= txtKhoa.getText();
            fis2= new FileInputStream("M:\\EnDes.txt");
            FileOutputStream fos2= new FileOutputStream("M:\\DeDes.txt");
            decrypt (key, fis2, fos2);
            BufferedReader br = null;
            br = new BufferedReader (new FileReader(fileName)); 
            StringBuffer sb = new StringBuffer(); 
            JOptionPane.showMessageDialog(null, "Đã Giải Mã");
            char[] ca = new char [5];
            while (br.ready()) {
                int len = br.read(ca);
                sb.append(ca, 0, len);
            }
            br.close();
            //xuat chuoi
            System.out.println("Du Lieu la:"+ "" +sb);
            String chuoi = sb.toString();
            
            txtVanBan.setText(chuoi);
        } catch (Throwable ex) {
            ex.printStackTrace();
            //Logger.getLogger (DESCS.class.getName()).log (Level. SEVERE, null, ex); 
        } finally {
            try {
                fis2.close();
            } catch (IOException ex) {
                ex.printStackTrace();
                //Logger.getLogger (DESCS.class.getName()).log (Level. SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnGiaiMaActionPerformed
//------------------------------------------------------------------------------
    private void btnGhiFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiFileActionPerformed
        // TODO add your handling code here:        
        try {
            BufferedWriter bw= null; 
            //ghi van ban da ma hoa
            String fileName = "M:\\Des.txt"; 
            //luu van ban
            String s = txtVanBan.getText();            
            bw = new BufferedWriter (new FileWriter(fileName)); // van ban sau khi ma hoa
            //ghi van ban
            bw.write(s);
                bw.close();
            JOptionPane.showMessageDialog(null," Đã ghi file");
            //txtMaHoa.setText(s);
        } catch (IOException ex) {
            ex.printStackTrace();
            //Logger.getLogger (DESCS.class.getName()).log (Level. SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGhiFileActionPerformed
//------------------------------------------------------------------------------
    private void btnMoFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoFileActionPerformed
        // TODO add your handling code here:        
        try {
        BufferedReader br = null;
        
        String fileName="M:\\EnDes.txt"; //GEN-
        br = new BufferedReader (new FileReader (fileName)); 
        StringBuffer sb = new StringBuffer();
        
        JOptionPane.showMessageDialog(null, "Đã mở file");
        char[] ca = new char [5];
        while (br.ready()) {
            int len = br.read(ca);
            sb.append(ca, 0, len);
        }
        br.close();
        //xuất chuỗi
        System.out.println("Du Lieu la: " + "" + sb);
        String chuoi = sb.toString();

        txtMaHoa.setText(chuoi);
        } catch (IOException ex) {
            ex.printStackTrace();
            //Logger.getLogger (DESCS.class.getName()).log (Level. SEVERE, null, ex);}
        }
    }//GEN-LAST:event_btnMoFileActionPerformed
//------------------------------------------------------------------------------
    private void btnAllShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAllShowActionPerformed

//------------------------------------------------------------------------------
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Des.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Des.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Des.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Des.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Des().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllShow;
    private javax.swing.JButton btnGhiFile;
    private javax.swing.JButton btnGiaiMa;
    private javax.swing.JButton btnMaHoa;
    private javax.swing.JButton btnMoFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextField txtMaHoa;
    private javax.swing.JTextField txtVanBan;
    // End of variables declaration//GEN-END:variables
}
