/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ThuatToan1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class frmPlayFail1 extends javax.swing.JFrame {
    char pf[][];
    private char[][] generateMatrixFromKey(String key){
        key = key.toUpperCase().replaceAll("[^A-Z]", "");
        key = key.replace('J', 'I');
        
        ArrayList<Character> characters = new ArrayList<>();
        
        for(char c : key.toCharArray()){
           if(!characters.contains(c)){
               characters.add(c);
           } 
        }
        for(char c = 'A'; c<= 'Z'; c++){
            if(c != 'J' && !characters.contains(c)){
                characters.add(c);
            }
        }
        char[][] matrix = new char[5][5];
        int index = 0;
        for(int i = 0; i<5; i++){
            for(int j = 0; j<5; j++){
                matrix[i][j] = characters.get(index++);
            }
        }
        return matrix;
    }
    private void generateRandomMatrix(){
        String key = this.txtkhoa.getText();
        pf = generateMatrixFromKey(key);
        
        System.out.println("Ma trận Playfair từ khoá:");
        for(int i = 0; i<5; i++){
            for(int j = 0; j<5; j++){
                System.out.print(pf[i][j] + " ");
            }
            System.out.println();
        }
    }
    public frmPlayFail1(){
        initComponents();
    }
//------------------------------------------------------------     
    private String mahoa(String banro){
        int n = banro.length();
        int i = 0;
        String banma="";
        char a,b;
        while(i<n){
            if(i==n-1){
                a=banro.charAt(i);
                b='X';
                i++;
            }else{
                a=banro.charAt(i);
                b=banro.charAt(i+1);
                
                if(a==b){
                    b='X';
                    i++;
                }else
                    i+=2;
            }
            
            banma+=thayThe(a,b);
        }
        return banma;
    }
    String thayThe(char a, char b){
        String vta = timViTri(a);
        String vtb = timViTri(b);
        char x,y;
        if(vta.charAt(0)==vtb.charAt(0)){   //cung dong
            x=pf[vta.charAt(0)-'0'][((vta.charAt(1)-'0')+1)%5];
            y=pf[(vtb.charAt(0)-'0')][((vtb.charAt(1)-'0')+1)%5];
            return x+""+y;
        }
        if(vta.charAt(1)==vtb.charAt(1)){
            x=pf[((vta.charAt(0)-'0')+1)%5][(vta.charAt(1)-'0')];
            y=pf[((vtb.charAt(0)-'0')+1)%5][(vtb.charAt(1)-'0')];
            return x+""+y;
        }
        x=pf[(vta.charAt(0)-'0')][(vta.charAt(1)-'0')];
        y=pf[(vtb.charAt(0)-'0')][(vtb.charAt(1)-'0')];
        return x+""+y;
    }
    private String timViTri(char a){
        for(int i=0;i<5;i++)
            for(int j=0; j<5; j++)
                if(pf[i][j]==a)
                    return i+""+j;
        return "";
    }
    //--------------
    private String giaima(String banma){
        int n = banma.length();
        String banro = "";
        char a,b;
        for(int i=0;i<n;i+=2){
            a=banma.charAt(i);
            b=banma.charAt(i+1);
            
            banro+=thayTheNguoc(a,b);
        }
        return banro;
    }
    String thayTheNguoc(char a, char b){
        String vta = timViTri(a);
        String vtb = timViTri(b);
        char x,y;
        if(vta.charAt(0)==vtb.charAt(0)){   //cung dong
            x=pf[(vta.charAt(0)-'0')][((vta.charAt(1)-'0')-1+5)%5];
            y=pf[(vtb.charAt(0)-'0')][((vtb.charAt(1)-'0')-1+5)%5];
            return x+""+y;
        }
        if(vta.charAt(1)==vtb.charAt(1)){
            x=pf[((vta.charAt(0)-'0')-1+5)%5][(vta.charAt(1)-'0')];
            y=pf[((vtb.charAt(0)-'0')-1+5)%5][(vtb.charAt(1)-'0')];
            return x+""+y;
        }
        x=pf[(vta.charAt(0)-'0')][(vta.charAt(1)-'0')];
        y=pf[(vtb.charAt(0)-'0')][(vtb.charAt(1)-'0')];
        return x+""+y;
    }
//------------------------------------------------------------     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtbanro = new javax.swing.JTextField();
        txtkhoa = new javax.swing.JTextField();
        txtbanma = new javax.swing.JTextField();
        btnmahoa = new javax.swing.JButton();
        btngiaima = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bản rõ");

        jLabel2.setText("Khoá");

        jLabel3.setText("Bản Mã");

        txtbanro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbanroActionPerformed(evt);
            }
        });

        txtkhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkhoaActionPerformed(evt);
            }
        });

        btnmahoa.setText("Mã hoá");
        btnmahoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmahoaActionPerformed(evt);
            }
        });

        btngiaima.setText("Giải mã");
        btngiaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngiaimaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Thuật toán Mã hoá Play Fail");

        jButton3.setText("Ghi File");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Mở File");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(txtbanro, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbanma, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnmahoa)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btngiaima)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbanro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmahoa)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtbanma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngiaima)
                    .addComponent(jButton5))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkhoaActionPerformed

    private void btnmahoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmahoaActionPerformed
       generateRandomMatrix();
        
       String banro = this.txtbanro.getText();
       banro = banro.toUpperCase();
       banro = banro.replace('J','I');
       String banma=mahoa(banro);
       this.txtbanma.setText(banma);
    }//GEN-LAST:event_btnmahoaActionPerformed

    private void btngiaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngiaimaActionPerformed
        String banma = this.txtbanma.getText();
        String banro = giaima(banma);
        int n = banro.length();
        String br = "";
        for(int i=0; i<n-2; i+=2)
            if(banro.charAt(i)==banro.charAt(i+2))
                br+=banro.charAt(i);
            else 
                br+=banro.charAt(i)+""+banro.charAt(i+1);
        if(banro.charAt(n-1)=='X')
            br+=banro.charAt(n-2);
        else
            br+=banro.charAt(n-2);
            br+=banro.charAt(n-1);
        this.txtbanro.setText(br);        
    }//GEN-LAST:event_btngiaimaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            BufferedWriter bw = null;
            
            String fileName = "M:\\Dulieu.txt";
            
            String s = txtbanma.getText();
            bw = new BufferedWriter(new FileWriter(fileName));
            bw.write(s);
            bw.close();
            JOptionPane.showMessageDialog(null, "Đã ghi File Thành công!!!");
        }catch (IOException ex){
            //Logger.getLogger(Caesar.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, "Lỗi!!!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            BufferedReader br = null;
            String fileName = "M:\\Dulieu.txt";
            br = new BufferedReader(new FileReader(fileName));
            
            StringBuffer sb = new StringBuffer();
            JOptionPane.showMessageDialog(null, "Da mo file thanh cong!!");
            
            char[] ca = new char[5];
            while (br.ready()){
                int len = br.read(ca);
                sb.append(ca, 0, len);
            }
            br.close();
            
            System.out.println("Du lieu la:"+""+sb);
            String chuoi = sb.toString();
        } catch (Exception e) {
            //Logger.getLogger(Caesar.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, "Lỗi!!!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtbanroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbanroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbanroActionPerformed
//-----------------------------------------
    public static void main(String args[]) {        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPlayFail1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPlayFail1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPlayFail1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPlayFail1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPlayFail1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngiaima;
    private javax.swing.JButton btnmahoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtbanma;
    private javax.swing.JTextField txtbanro;
    private javax.swing.JTextField txtkhoa;
    // End of variables declaration//GEN-END:variables
    }
