package lab04;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.security.AlgorithmParameterGenerator;
import java.security.AlgorithmParameters;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

/**
 *
 * @author PHUC VINH
 */
public class frmAlice extends javax.swing.JFrame {
    
    KeyAgreement aliceKeyArgee;
    PublicKey bobPubKey;
    SecretKey aliceDesKey;
    Cipher aliceCipher;
    /**
     * Creates new form NewJFrame
     */
    public frmAlice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKhoaKAB = new javax.swing.JTextField();
        txtKhoaChung = new javax.swing.JTextField();
        txtKhoaB = new javax.swing.JTextField();
        txtKhoaA = new javax.swing.JTextField();
        btnKhoaA = new javax.swing.JButton();
        btnKhoaKB = new javax.swing.JButton();
        btnKhoaChung = new javax.swing.JButton();
        btnMaHoaKAB = new javax.swing.JButton();
        btnMaHoaGiaiMa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Khoa Alice");

        jLabel2.setText("ALICE");

        jLabel3.setText("Khoa Bob");

        jLabel4.setText("Khoa KAB");

        jLabel5.setText("Ma Hoa KAB");

        txtKhoaChung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhoaChungActionPerformed(evt);
            }
        });

        btnKhoaA.setText("Tao Khoa A");
        btnKhoaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaAActionPerformed(evt);
            }
        });

        btnKhoaKB.setText("Hien Thi KB");
        btnKhoaKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaKBActionPerformed(evt);
            }
        });

        btnKhoaChung.setText("Khoa Chung");
        btnKhoaChung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaChungActionPerformed(evt);
            }
        });

        btnMaHoaKAB.setText("Ma Hoa KAB");
        btnMaHoaKAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaKABActionPerformed(evt);
            }
        });

        btnMaHoaGiaiMa.setText("Ma hoa/ Giai Ma");
        btnMaHoaGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaGiaiMaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKhoaKAB, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(txtKhoaChung)
                                    .addComponent(txtKhoaB)
                                    .addComponent(txtKhoaA))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnKhoaA)
                                    .addComponent(btnKhoaKB)
                                    .addComponent(btnKhoaChung)
                                    .addComponent(btnMaHoaKAB)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnMaHoaGiaiMa)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKhoaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhoaA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKhoaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhoaKB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKhoaChung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhoaChung))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKhoaKAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaHoaKAB))
                .addGap(18, 18, 18)
                .addComponent(btnMaHoaGiaiMa)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//------------------------------------------------------------------------
    private void btnKhoaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaAActionPerformed
        // TODO add your handling code here:
        try {
            AlgorithmParameterGenerator paramGen = 
                    AlgorithmParameterGenerator.getInstance("DH");
            paramGen.init(512);
            AlgorithmParameters params = paramGen.generateParameters();
            
            DHParameterSpec dhSkipParamSpec = 
                    (DHParameterSpec) params.getParameterSpec(DHParameterSpec.class);
            
            System.out.println("Generating a DH KeyPair...");
            KeyPairGenerator aliceKpairGen = KeyPairGenerator.getInstance("DH");
            aliceKpairGen.initialize(dhSkipParamSpec);
            KeyPair aliceKPair = aliceKpairGen.generateKeyPair();
            
            System.out.println("Initializing the KeyArgement Engine with DH private key");
            aliceKeyArgee = KeyAgreement.getInstance("DH");
            aliceKeyArgee.init(aliceKPair.getPrivate());
            
            byte[] alicePubKeyEnc = aliceKPair.getPublic().getEncoded();
            FileOutputStream fos = new FileOutputStream("D:/A.pub");
            fos.write(alicePubKeyEnc);
            fos.close();            
            txtKhoaA.setText(alicePubKeyEnc.toString());
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnKhoaAActionPerformed
//------------------------------------------------------------------------
    private void btnKhoaKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaKBActionPerformed
        // TODO add your handling code here:
        try {
            FileInputStream fis = new FileInputStream("D:/B.pub");
            byte[] bkeyP = new byte[fis.available()];
            fis.read(bkeyP);
            fis.close();
            txtKhoaB.setText(bkeyP.toString());
        } catch (Exception ex) {}
    }//GEN-LAST:event_btnKhoaKBActionPerformed
//------------------------------------------------------------------------
    private void btnKhoaChungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaChungActionPerformed
        // TODO add your handling code here:
        try{
            FileInputStream fis=new FileInputStream("D:/B.pub");
            byte[] bobPubKeyEnc=new byte[fis.available()];
            fis.read (bobPubKeyEnc);
            fis.close();
            
            KeyFactory aliceKeyFac =  KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec (bobPubKeyEnc);
            bobPubKey = aliceKeyFac.generatePublic (x509KeySpec);
            System.out.println("Executing PHASE1 of key agreement...");
            aliceKeyArgee.doPhase(bobPubKey, true);
            byte[] aliceSharedSecret = aliceKeyArgee.generateSecret();
            
            System.out.println("khoa chung: secret (DEBUG ONLY) :" + CryptoUtil.toHexString (aliceSharedSecret)); 
            txtKhoaChung.setText(CryptoUtil.toHexString(aliceSharedSecret));
        }
        catch (Exception ex) {}
    }//GEN-LAST:event_btnKhoaChungActionPerformed
//------------------------------------------------------------------------
    private void txtKhoaChungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhoaChungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhoaChungActionPerformed
//-------------------------------Ma Hoa KAB-----------------------------------------
    private void btnMaHoaKABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaKABActionPerformed
        // TODO add your handling code here        
        try{
            aliceKeyArgee.doPhase(bobPubKey, true);
            aliceDesKey = aliceKeyArgee.generateSecret("DES");
            txtKhoaKAB.setText(aliceDesKey.toString());
            // khoa chung
            BufferedWriter bw= null;
            //ghi van ban da ma hoa
            String fileName = "D:\\KhoaA.txt"; 
            //luu van 
             // van ban sau khi ma hoa
            bw = new BufferedWriter(new FileWriter(fileName)); 
            // ghi van ban
            bw.write(aliceDesKey.toString());
            bw.close();
            
        } catch (Exception ex) {
            System.out.print(ex);
        }
    }//GEN-LAST:event_btnMaHoaKABActionPerformed
//------------------------------------------------------------------------
    private void btnMaHoaGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaGiaiMaActionPerformed
        // TODO add your handling code here:
        DESCS des = new DESCS();
        des.setVisible(true);
    }//GEN-LAST:event_btnMaHoaGiaiMaActionPerformed
//------------------------------------------------------------------------
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAlice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAlice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAlice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAlice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAlice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhoaA;
    private javax.swing.JButton btnKhoaChung;
    private javax.swing.JButton btnKhoaKB;
    private javax.swing.JButton btnMaHoaGiaiMa;
    private javax.swing.JButton btnMaHoaKAB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtKhoaA;
    private javax.swing.JTextField txtKhoaB;
    private javax.swing.JTextField txtKhoaChung;
    private javax.swing.JTextField txtKhoaKAB;
    // End of variables declaration//GEN-END:variables
}
