package lab04;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.security.AlgorithmParameterGenerator;
import java.security.AlgorithmParameters;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.interfaces.DHPublicKey;
import javax.crypto.spec.DHParameterSpec;

/**
 *
 * @author PHUC VINH
 */
public class frmBob extends javax.swing.JFrame {
    
    KeyAgreement bobKeyArgee;
    PublicKey aliceBubKey;
    SecretKey bobDesKey;
    Cipher bobCipher;
    /**
     * Creates new form NewJFrame
     */
    public frmBob() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaHoaKAB = new javax.swing.JTextField();
        txtKhoaChung = new javax.swing.JTextField();
        txtKhoaA = new javax.swing.JTextField();
        txtKhoaB = new javax.swing.JTextField();
        btnKhoaB = new javax.swing.JButton();
        btnKhoaKA = new javax.swing.JButton();
        btnMaHoaKAB = new javax.swing.JButton();
        btnKhoaChung = new javax.swing.JButton();
        btnMaHoaGiaiMa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Khoa BOB");

        jLabel2.setText("BOB");

        jLabel3.setText("Khoa Alice");

        jLabel4.setText("Khoa KAB");

        jLabel5.setText("Ma Hoa KAB");

        txtMaHoaKAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHoaKABActionPerformed(evt);
            }
        });

        txtKhoaChung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhoaChungActionPerformed(evt);
            }
        });

        btnKhoaB.setText("Tao Khoa B");
        btnKhoaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaBActionPerformed(evt);
            }
        });

        btnKhoaKA.setText("Hien Thi KA");
        btnKhoaKA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaKAActionPerformed(evt);
            }
        });

        btnMaHoaKAB.setText("Ma Hoa KAB");
        btnMaHoaKAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaKABActionPerformed(evt);
            }
        });

        btnKhoaChung.setText("Khoa Chung");
        btnKhoaChung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaChungActionPerformed(evt);
            }
        });

        btnMaHoaGiaiMa.setText("Ma hoa/ Giai Ma");
        btnMaHoaGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaGiaiMaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMaHoaKAB, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addComponent(txtKhoaChung)
                                .addComponent(txtKhoaA)
                                .addComponent(txtKhoaB))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnMaHoaGiaiMa)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMaHoaKAB)
                            .addComponent(btnKhoaB)
                            .addComponent(btnKhoaKA)
                            .addComponent(btnKhoaChung))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKhoaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhoaB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKhoaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhoaKA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKhoaChung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhoaChung))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaHoaKAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaHoaKAB))
                .addGap(18, 18, 18)
                .addComponent(btnMaHoaGiaiMa)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//--------------------------------------------------------------------
    private void btnKhoaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaBActionPerformed
        // TODO add your handling code here:
        try {
            boolean read = false;
            
            while (read){
                try {
                    FileInputStream fis = new FileInputStream("D:/A.pub");
                    fis.close();
                    read =true;                    
                } catch (Exception ex) {}
            }
            
            FileInputStream fis=new FileInputStream("D:/A.pub");
            byte[] alicePubKeyEnc=new byte[fis.available ()];
            fis.read(alicePubKeyEnc);
            fis.close();
            KeyFactory bobKeyFac = KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec (alicePubKeyEnc); 
            aliceBubKey = bobKeyFac.generatePublic(x509KeySpec);
            DHParameterSpec dhParamSpec = ((DHPublicKey) aliceBubKey).getParams();
            System.out.println("Generate DH keypair...");
            KeyPairGenerator bobKpairGen = KeyPairGenerator.getInstance("DH");
            bobKpairGen.initialize (dhParamSpec);
            KeyPair bobKpair = bobKpairGen.generateKeyPair();
            System.out.println("Initializing KeyAgreement engine...");
            bobKeyArgee = KeyAgreement.getInstance("DH");
            bobKeyArgee.init(bobKpair.getPrivate());
            byte[] bobPubKeyEnc= bobKpair.getPublic().getEncoded(); 
            FileOutputStream fos=new FileOutputStream("D:/B.pub");
            fos.write (bobPubKeyEnc);
            fos.close();
            txtKhoaB.setText(bobPubKeyEnc.toString());
        }catch (Exception ex) {}
    }//GEN-LAST:event_btnKhoaBActionPerformed
//--------------------------------------------------------------------
    private void btnKhoaKAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaKAActionPerformed
        // TODO add your handling code here:
        try {
            FileInputStream fis = new FileInputStream("D:/A.pub");
            byte[] akeyP = new byte[fis.available()];
            fis.read(akeyP);
            fis.close();
            txtKhoaA.setText(akeyP.toString());
        } catch (Exception ex) {}
    }//GEN-LAST:event_btnKhoaKAActionPerformed
//----------------------------MA HOA  KAB----------------------------------------
    private void btnMaHoaKABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaKABActionPerformed
        // TODO add your handling code here:
        try{
            bobKeyArgee.doPhase (aliceBubKey, true);
            bobDesKey = bobKeyArgee.generateSecret("DES");
            txtMaHoaKAB.setText(bobDesKey.toString());
            // khoa chung A B
            BufferedWriter bw= null;
            //ghi van ban da ma hoa
            String fileName = "D:\\KhoaB.txt"; 
            //luu van 
            // van ban sau khi ma hoa
            bw = new BufferedWriter (new FileWriter (fileName)); 
            // ghi van ban
            bw.write(bobDesKey.toString());
            bw.close();
            }
        catch (Exception ex) {}
    }//GEN-LAST:event_btnMaHoaKABActionPerformed
//--------------------------------------------------------------------
    private void txtKhoaChungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhoaChungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhoaChungActionPerformed
//----------------------KHOA CHUNG----------------------------------------------
    private void btnKhoaChungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaChungActionPerformed
        // TODO add your handling code here
        try {  
            bobKeyArgee.doPhase(aliceBubKey, true);
            byte[] bobSharedSecret = bobKeyArgee.generateSecret();
            System.out.println("Khoa chung: Shared secret (DEBUG ONLY): "+CryptoUtil.toHexString(bobSharedSecret));
            txtKhoaChung.setText(CryptoUtil.toHexString(bobSharedSecret));          
        } catch (Exception ex) {
            System.out.print(ex);
        }
    }//GEN-LAST:event_btnKhoaChungActionPerformed
//--------------------------------------------------------------------
    private void btnMaHoaGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaGiaiMaActionPerformed
        // TODO add your handling code here:
        DESCS des = new DESCS();
        des.setVisible(true);
    }//GEN-LAST:event_btnMaHoaGiaiMaActionPerformed

    private void txtMaHoaKABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHoaKABActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHoaKABActionPerformed
//--------------------------------------------------------------------
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhoaB;
    private javax.swing.JButton btnKhoaChung;
    private javax.swing.JButton btnKhoaKA;
    private javax.swing.JButton btnMaHoaGiaiMa;
    private javax.swing.JButton btnMaHoaKAB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtKhoaA;
    private javax.swing.JTextField txtKhoaB;
    private javax.swing.JTextField txtKhoaChung;
    private javax.swing.JTextField txtMaHoaKAB;
    // End of variables declaration//GEN-END:variables
}
